version: '3'
services:
  backend:
    image: openjdk:11
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app/backend
    command: './mvnw spring-boot:run'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb

volumes:
  database-data:
